---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: start AWS instance
    amazon.aws.ec2_instance:
      name: "ansible-generated-instance"
      key_name: clave-lucatic
      vpc_subnet_id: subnet-0dd37ba3dac470b30
      instance_type: t2.micro
      security_group: sg-0194696b9502d969d
      network:
        assign_public_ip: true
      image_id: ami-0b752bf1df193a6c4
